rework script to adjust for linux

diff --git a/linux b/linux
--- a/linux
+++ b/linux
@@ -1,15 +1,14 @@
-#!/bin/sh
+#!/usr/bin/env bash
+# Turn your laptop into an awesome development machine.
+# Usage: $ bash linux 2>&1 | tee ~/setup.log
 
-# Turn your laptop into an awesome development machine, to get logs do
-# sh linux 2>&1 | tee ~/setup.log
-
-set -o xtrace  # aka 'set -x' to trace what gets executed
+#set -o xtrace  # aka 'set -x' to trace what gets executed ... for debugging
 set -o errexit # aka 'set -e' to exit when command fails
 # shellcheck disable=SC2154
-#trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT
+trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT
 
-echo "create some helper functions ..."
-#######################################
+echo "### create some helper functions ..."
+##########################################
 append_to_zshrc() {
   local text="$1" zshrc
   local skip_new_line="${2:-0}"
@@ -27,8 +26,6 @@ append_to_zshrc() {
       printf "\n%s\n" "$text" >> "$zshrc"
     fi
   fi
-
-  source "$zshrc"
 }
 
 install_asdf_plugin() {
@@ -59,24 +56,26 @@ gem_install_or_update() {
   fi
 }
 
-echo "create lolca bin directory ..."
-#####################################
-if [ ! -d "$HOME/.bin/" ]; then
-  mkdir "$HOME/.bin"
-  # shellcheck disable=SC2016
-  append_to_zshrc 'export PATH="$HOME/.bin:$PATH"'
-fi
-
-echo "change shell to zsh ..."
-##############################
+echo "### change shell to zsh ..."
+#################################
 if [ ! -f "$HOME/.zshrc" ]; then
   touch "$HOME/.zshrc"
 fi
 
 chsh -s "$(which zsh)"
 
-echo "install linux packages ..."
-#################################
+echo "### create lolca bin directory ..."
+########################################
+if [ ! -d "$HOME/.bin/" ]; then
+  mkdir "$HOME/.bin"
+
+  # shellcheck disable=SC2016
+  append_to_zshrc 'export PATH="$HOME/.bin:$PATH"'
+fi
+
+echo "### install linux packages ..."
+####################################
+sudo apt update && sudo apt upgrade
 sudo apt install --assume-yes \
   exuberant-ctags \
   git \
@@ -87,103 +86,89 @@ sudo apt install --assume-yes \
   vim \
   zsh
 
-echo "install asdf version manager ..."
-#######################################
+echo "### install asdf version manager ..."
+##########################################
 sudo apt install --assume-yes \
   automake autoconf libreadline-dev libncurses-dev libssl-dev \
   libyaml-dev libxslt-dev libffi-dev libtool make unixodbc-dev
 
 if [ ! -d "$HOME/.asdf" ]; then
   git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.4.0
+
+  # shellcheck disable=SC2016
+  append_to_zshrc '# Add asdf version manager'
   append_to_zshrc "source $HOME/.asdf/asdf.sh" 1
   append_to_zshrc "source $HOME/.asdf/completions/asdf.bash" 1
 fi
 
-echo "install latest Ruby ..."
-##############################
+# shellcheck disable=SC1090
+source ~/.asdf/asdf.sh
+
+echo "### install latest Ruby ..."
+#################################
 install_asdf_plugin "ruby" "https://github.com/asdf-vm/asdf-ruby.git"
 install_asdf_language "ruby"
 
 gem update --system
 gem_install_or_update "bundler"
-number_of_cores=$(sysctl -n hw.ncpu)
+number_of_cores="$(cat /proc/cpuinfo | grep processor | wc -l)"
 bundle config --global jobs $((number_of_cores - 1))
 
-echo "install latest Node ..."
-################################
+echo "### install latest Node ..."
+#################################
 install_asdf_plugin "nodejs" "https://github.com/asdf-vm/asdf-nodejs.git"
 bash "$HOME/.asdf/plugins/nodejs/bin/import-release-team-keyring"
 install_asdf_language "nodejs"
 
-echo "install Linuxbrew ..."
-############################
-# see http://linuxbrew.sh/
-# HOMEBREW_PREFIX="/usr/local"
-#
-# if [ -d "$HOMEBREW_PREFIX" ]; then
-#   if ! [ -r "$HOMEBREW_PREFIX" ]; then
-#     sudo chown -R "$LOGNAME:admin" /usr/local
-#   fi
-# else
-#   sudo mkdir "$HOMEBREW_PREFIX"
-#   sudo chflags norestricted "$HOMEBREW_PREFIX"
-#   sudo chown -R "$LOGNAME:admin" "$HOMEBREW_PREFIX"
-# fi
-#
-# if ! command -v brew >/dev/null; then
-#   fancy_echo "Installing Homebrew ..."
-#     curl -fsS \
-#       'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby
-#
-#     append_to_zshrc '# recommended by brew doctor'
-#
-#     # shellcheck disable=SC2016
-#     append_to_zshrc 'export PATH="/usr/local/bin:$PATH"' 1
-#
-#     export PATH="/usr/local/bin:$PATH"
-# fi
-#
-# if brew list | grep -Fq brew-cask; then
-#   fancy_echo "Uninstalling old Homebrew-Cask ..."
-#   brew uninstall --force brew-cask
-# fi
-#
-# fancy_echo "Updating Homebrew formulae ..."
-# brew update --force # https://github.com/Homebrew/brew/issues/1151
+echo "### install Linuxbrew ..."
+###############################
+if ! command -v brew >/dev/null; then
+  # see http://linuxbrew.sh/
+  sudo apt install --assume-yes build-essential
+  sudo curl -fsSL 'https://raw.githubusercontent.com/Linuxbrew/install/master/install' | ruby
+  export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
 
-echo "brew some packages"
-#########################
-# brew bundle --file=- <<EOF
-# tap "thoughtbot/formulae"
-# tap "homebrew/services"
-# tap "caskroom/cask"
-#
-# # Unix
-# brew "rcm"
-# brew "reattach-to-user-namespace"
-# brew "watchman"
-#
-# # GitHub
-# brew "hub"
-#
+  # shellcheck disable=SC2016
+  append_to_zshrc '# Add linuxbrew to PATHs'
+  append_to_zshrc 'export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"' 1
+  append_to_zshrc 'export MANPATH="/home/linuxbrew/.linuxbrew/share/man:$MANPATH"' 1
+  append_to_zshrc 'export INFOPATH="/home/linuxbrew/.linuxbrew/share/info:$INFOPATH"' 1
+fi
+
+echo "### brew some packages"
+############################
+brew update --force # https://github.com/Homebrew/brew/issues/1151
+brew bundle --file=- <<EOF
+tap "thoughtbot/formulae"
+tap "homebrew/services"
+tap "caskroom/cask"
+
+# Unix
+#brew "rcm" via apt!
+#brew "reattach-to-user-namespace"
+brew "watchman"
+
+# GitHub
+brew "hub"
+
 # # Heroku
-# brew "heroku"
-# brew "parity"
-#
+#brew "heroku"
+#brew "parity"
+
 # # Testing
 # brew "qt@5.5" if MacOS::Xcode.installed?
-#
+
 # # Programming language prerequisites and package managers
 # brew "libyaml" # should come after openssl
 # brew "coreutils"
 # brew "yarn"
 # cask "gpg-suite"
-#
+
 # # Databases
 # brew "postgres", restart_service: :changed
 # brew "redis", restart_service: :changed
-# EOF
-#
+EOF
+
 # if brew list | grep --silent "qt@5.5"; then
 #   fancy_echo "Symlink qmake binary to /usr/local/bin for Capybara Webkit..."
 #   brew unlink qt@5.5
@@ -194,8 +179,8 @@ echo "brew some packages"
 # brew unlink heroku
 # brew link --force heroku
 
-echo "run customizations from ~/.laptop.local ..."
-##################################################
+echo "### run customizations from ~/.laptop.local ..."
+#####################################################
 if [ -f "$HOME/.laptop.local" ]; then
   # shellcheck disable=SC1090
   source "$HOME/.laptop.local"
