Not so much spacing

diff --git a/mac b/mac
--- a/mac
+++ b/mac
@@ -1,7 +1,7 @@
 #!/usr/bin/env zsh
 
 successfully() {
-  $* || (echo "\nfailed\n" 1>&2 && exit 1)
+  $* || (echo "\nfailed" 1>&2 && exit 1)
 }
 
 echo "\nFixing OSX zsh environment bug ..."
